name: encrypted_shared_preferences
description: This plugin stores Shared Preferences as encrypted values on device storage.
version: 3.0.1
homepage: https://github.com/roulljdh/encrypted_shared_preferences

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  encrypt:
    git:
      url: https://github.com/giangphan11/encrypt
      ref: cd711c3
  shared_preferences: ^2.5.3

dev_dependencies: null
