name: encrypted_shared_preferences
description: This plugin stores Shared Preferences as encrypted values on device storage.
version: 2.1.0
homepage: https://github.com/roulljdh/encrypted_shared_preferences

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  encrypt: ^5.0.1
  shared_preferences: ^2.0.8

dev_dependencies: null
